### ISSUE TITLE
input mesh dimension

### ISSUE THREAD

**Issue by smoothumut** [Tai-Hsien/MeshSegNet#10]
Hi Tai, thanks again for your great work and contribution. and also thanks for sharing.
My question is that what would be the best mesh dimension for **labeling** and **training** as input.
10.000 cells? or 100.000 cells? or just using the raw mesh which is like 600.000 cells?
Your paper says "The input F0 of our MeshSNet model are the raw mesh surface data" 
so do you mean just using the mesh as it is for labeling and then training? I just want to be sure,
thanks in advance
Regards

**Comment by Tai-Hsien** [comment]
Hello,
Thanks for be interested in our work.

For question 1, we used 10,000 cells for both labeling and training.
For question 2, the  mesh surface data in the paper means the downsampled mesh (10,000 cells).

Theoretically, any number of cells can be used in training and prediction. However, we used downsampled size due to the limited  memory (Particularly GPU memory).

**Comment by smoothumut** [comment]
Thanks a lot Tai, great work. also appreciated for the pre-trained model of the lower arch. Regards
