### ISSUE TITLE
Performance on training

### ISSUE THREAD

**Issue by smoothumut** [Tai-Hsien/MeshSegNet#14]
Hi again Tai,
We have some training performance issues. We try to train model with our vtp files. We have 100 vtp files that decimated to 10000 and then labeled. no flipping yet. Our training computer has one rtx 2080 Ti  . When we try to train the model, it is too slow. one epoch takes 3-4 hours. The system uses gpu ram but it  does almost use none of the gpu power. Do we make some mistakes or is this normal?

**Comment by Tai-Hsien** [comment]
Hello,
I believe you do everything right. The reason that the GPU power is not pretty high is because we re-sample partial points (i.e., generate new point cloud) as training data in all batches. The related code is in `Mesh_dataset.py`, and this procedure is done by CPU. Therefore, GPU needs to wait when the "new" generated training data are ready. You can read it in detail in our papers. We did this because we didn't have a big-size dataset. If you don't want to re-generate samples every time. You can do the sampling before training and save as h5 files. Then, modify `Mesh_dataset.py` to ready the h5 files.

**Comment by smoothumut** [comment]
Great Advice, thanks a lot Tai, Deeply Appreciated
Best Regards

**Comment by carina1754** [comment]
Hello.
No matter how hard I tried, I couldn't find a way to improve the speed, so I'm asking again. Could you help me how to create h5 file? And Could you tell me how to apply in step3 train?

**Comment by Tai-Hsien** [comment]
Hello,
If you would like to improve the speed of training, one way you can do is as follows.
First, modify step_1.py to read original vtp files, augment the samples, and do the resampling process as Mesh_dataset.py does, then generate the resampling results to h5 files. Therefore, in the training, resampling process is no longer needed.
Second, modify Mesh_dataset.py to read h5 files instead of vtp files.

You can monitor your GPU power to make sure if GPU is fully working or not.

Best,

**Comment by carina1754** [comment]
thank you so much!!
