### ISSUE TITLE
Trouble in Data annotation

### ISSUE THREAD

**Issue by hyzwj** [Tai-Hsien/MeshSegNet#3]
Hello, I just recently started to study the segmentation of dental crowns, but I don't know how to make my own segmentation data set. For me, how to label is a problem.Would you help me do it?

**Comment by Tai-Hsien** [comment]
Hello hyzwj,

This is a very good question. There are two ways to do that based on my understanding now. However, none of them are really efficient.

(1) You can use Meshmixer or similar program to cut the original mesh (STL file) into several tooth segments and save them as STL files. Then, to use vtk to read the original mesh and tooth STL files, determine the corresponding label of each triangle based on the their position, and store the label into an array with size of number of triangles.

(2) You can download my other work, called Mesh_Label_Fixer (https://github.com/Tai-Hsien/Mesh_Label_Fixer) to label it, but in this program, you need to click all triangles that you want to label, which is extremely labor intensive. You will need to downsampled the original mesh to at least 10,000 cells first. Otherwise, it's almost impossible to click all triangles. I basically use the second way is correct the wrong predictions from MeshSegNet.

The first way will be more doable, compared to the second one, but you need to be familiar with vtk or similar packages. I am still trying to find a better way (like GUI program) to let our students to annotate new samples as well. Feel free to discuss with me if you have any problem or thinking!

Best,

Bruce Wu

**Comment by hyzwj** [comment]
Thanks and I will try using your approach, best wishes!

**Comment by Tai-Hsien** [comment]
I found I have some code for the 1st way. Please refer to https://github.com/Tai-Hsien/easy_mesh_vtk

I copy the related code as below:

# create a new mesh by loading a main STL file and label it with other STL files
from easy_mesk_vtk.easy_mesh.vtk import *

mesh = Easy_Mesh('Sample_01_d.stl') # Sample_01_d.stl is the whole mesh
mesh1 = Easy_Mesh('Sample_01_T2_d.stl') # Sample_01_T2_d.stl is a tooth mesh
mesh2 = Easy_Mesh('Sample_01_T3_d.stl') # Sample_01_T3_d.stl is another tooth mesh
## make a label dict in which key=str(label_ID), value=cells (i.e., [n, 9] array)
label_dict = {'1': mesh1.cells, '2': mesh2.cells} 
mesh.set_cell_labels(label_dict)
mesh.to_vtp('example_with_labels.vtp')

However, I didn't check this function comprehensively. You can try it and let me know if it has errors.

Best,

Bruce Wu

**Comment by hyzwj** [comment]
Thank you for your reponse ,I will try it .

**Comment by Tai-Hsien** [comment]
Hello hyzwj,

I just found a repo that describe how to make your own mesh annotation. Please refer to https://github.com/LSnyd/PartSegmentationToolbox

I followed the instruction to try blender today. It works, but you might spend some time to be familiar with the operations in blender. Comparing to the first method I mentioned above, it's still hard to say which way is more efficient. No matter what, you get one more choice. Please also let me know if you find a better way. Thanks.

Best,

Bruce Wu

**Comment by Tai-Hsien** [comment]
> Thank you for your reponse ,I will try it .

I have designed a GUI program to work on mesh annotation, https://github.com/Tai-Hsien/Mesh_Labeler.
Feel free to ask me if you plan to use it and have any questions.

Best,

Bruce Wu

**Comment by hyzwj** [comment]
Thank you very much for your suggestion, I will try it in the next time.

**Comment by hyzwj** [comment]
Hello, thanks for the previous reply.  Now we have encountered another problem. We have annotated the point cloud data of the tooth and started training.  During training, we found that each data file contains too many points (hundreds of thousands of points) and needs to be down-sampled, but the original labels cannot match the point cloud after down-sampling. How can we ensure that the labels still match after down-sampling, or do we have to down-sample first and then label the data?

**Comment by Tai-Hsien** [comment]
You can use the original point coordinates and label as training data to train a SVM or KNN model, to predict the downsampled point coordinates (as unseen data).

**Comment by ananyajana** [comment]
Hi @Tai-Hsien , Hope you are doing great.
I have the entire mesh as well as the part meshes in form of stl file.
could you guide on how to incorporate the labels in the entire/whole mesh file.
 The link https://github.com/Tai-Hsien/easy_mesh_vtk didn't work.
How do you implement the mesh.set_cell_labels functions?

**Comment by Tai-Hsien** [comment]
@ananyajana 
I am no longer maintain and use easy_mesh_vtk (https://github.com/Tai-Hsien/easy_mesh_vtk). Instead, I am using vedo (https://vedo.embl.es/) for all the same jobs. You can try it.

**Comment by ananyajana** [comment]
thanks @Tai-Hsien
