### ISSUE TITLE
we made the model work, but wrong results

### ISSUE THREAD

**Issue by smoothumut** [Tai-Hsien/MeshSegNet#6]
Hi, first of all thank you very much for sharing your amazing research and hard work with all of us. My question is; we are trying to run your model (that comes with the code) then it creates the vtp file successfully but when we open the vtp file in vtk.js geometry viewer, it displays labeling very wrong! 
![Screenshot_3](https://user-images.githubusercontent.com/10278059/101330143-53a31500-3883-11eb-8267-502b6f174ec3.png)
![Screenshot_1](https://user-images.githubusercontent.com/10278059/101330150-54d44200-3883-11eb-8f3b-ac8b48d47eee.png)
![Screenshot_2](https://user-images.githubusercontent.com/10278059/101330152-556cd880-3883-11eb-8866-c27293f07396.png)

what would we do wrong? we use step5_predict script ( we have some troubles with pygco, so thats why we use just step 5. but those steps also gives similar results without pygco)
thanks in advance

**Comment by wangzhijiang110** [comment]
How to open vtk files   ？Can you share the web  to  me.Thank you.

**Comment by Tai-Hsien** [comment]
@smoothumut
Hello,
Thanks for letting me know your problem. Did you re-train the model by using your own data or just use the model I provided?
I think everything is correct, but you might need to move the center of model to the origin. As I know, centers of mass of intra-oral scans vary from different scanners, so I did it before I trained the model. Could you try it again and let me know the result?

**Comment by Tai-Hsien** [comment]
> How to open vtk files ？Can you share the web to me.Thank you.

Hello @wangzhijiang110 

I think they use vtk.js to open it with a browser. I personally like to use Paraview (https://www.paraview.org/download/) to visualize VTK (or VTP) files.

**Comment by Tai-Hsien** [comment]
> @smoothumut
> Hello,
> Thanks for letting me know your problem. Did you re-train the model by using your own data or just use the model I provided?
> I think everything is correct, but you might need to move the center of model to the origin. As I know, centers of mass of intra-oral scans vary from different scanners, so I did it before I trained the model. Could you try it again and let me know the result?

@smoothumut I actually saw this process in step5, so it should not be the reason. Is it possible to send a file from your dataset to me to test?

**Comment by smoothumut** [comment]
Hi Tai-Hsien,
Thanks for your quick reply. I havent re-trained the model yet, I have been using your model. 

Here is the stl file. 
[Example_02.zip](https://github.com/Tai-Hsien/MeshSegNet/files/5657379/Example_02.zip)

I have run the step 6 successfully with and without pygco as you coded, here is the result. I am not sure if I do it correctly or not, so it would be good idea for you to test the same file in your environment.
here are my results: 
downsampled and predicted:
![Screenshot_1_a](https://user-images.githubusercontent.com/10278059/101451914-fcae4600-393d-11eb-8dcf-b377521f0b2c.png)
![Screenshot_1_b](https://user-images.githubusercontent.com/10278059/101451933-020b9080-393e-11eb-8a63-d55f4b7af660.png)


downsampled and predicted and refined:
![Screenshot_2_a](https://user-images.githubusercontent.com/10278059/101451947-08017180-393e-11eb-99ce-b87fb8ccf272.png)
![Screenshot_2_b](https://user-images.githubusercontent.com/10278059/101451953-0afc6200-393e-11eb-9b66-9080bf91e9bf.png)



downsampled and predicted and refined and unsampled:
![Screenshot_3_a](https://user-images.githubusercontent.com/10278059/101451964-0fc11600-393e-11eb-9f62-31c5c278230a.png)
![Screenshot_3_b](https://user-images.githubusercontent.com/10278059/101451987-18195100-393e-11eb-93fa-de63a38785c0.png)

Again, THANK YOU VERY MUCH for your research and support

**Comment by Tai-Hsien** [comment]
Hello @smoothumut ,

I figured out two problems. Actually, you did everything right. That was my fault that I didn't organize these codes well.
(1) It looks like the trained model I uploaded was a test one and it's not well trained yet. I have uploaded another called "MeshSegNet_Max_15_classes_72samples_lr1e-2_best.tar" in models folder. Please download it if you plan to use our trained model.
(2) I updated several files (Mesh_dataset.py, step4_test.py, step5_predict.py, and two step6 files.). In the previous version, there was a redundant normalization (i.e., Line 70 in Mesh_dataset.py, Line 112 in step6_predict_with_post_processing_pygco.py). This normalization should be consistent with the training code, which means if we have this redundant normalization in the training process, we also need to use it when predicting. Since I removed it when I trained the model, it also needs to be removed when using the new well trained model.

To fix the two problems, you should be able to see the results as below.

without graph-cut refinement
![image](https://user-images.githubusercontent.com/9615481/101562799-1b402b80-3996-11eb-9ad4-ebf599c14065.png)

with graph-cut refinement
![image](https://user-images.githubusercontent.com/9615481/101562881-3c088100-3996-11eb-83a6-f24657680054.png)

Although it's still not perfect, the refined one looks much better than before. May I ask which field you are working on? Orthodontics or deep learning?

Hope it helps.

**Comment by smoothumut** [comment]
Hi @Tai-Hsien ,
I run your newest model and I got the same results with you, and it looks great : )  I believe with more data it will give perfect results. Personally, I am a deep learner and I  work for a startup in Europe. we work on a project that aims orthodontists and your research gives us great insights and makes us save tremendous time in research. Honestly, I cant thank you enough. 
with my best regards
:pray: :bow:

**Comment by Tai-Hsien** [comment]
Hello @smoothumut ,
You are very welcome. I am preparing the manuscript for an improved version of MeshSegNet, which shows even better performance in terms of accuracy and computing time. I will release it as well when it's done.
